# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

# These settings are synced to GitHub by https://probot.github.io/apps/settings/

---
repository:
  # See https://docs.github.com/en/rest/reference/repos#update-a-repository for all available settings.
  name: distroless
  description: Lightweight and secure container images
  homepage: https://github.com/nlamirault/distroless
  topics: distroless, wolfi, apk, melange
  private: false
  has_issues: true
  has_projects: true
  has_wiki: true
  has_downloads: true
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

labels:

## KIND
- name: "kind/maintenance"
  description: "Categorizes issue or PR as related to maintenance"
  color: "FF0040"

- name: "kind/bug"
  description: "Categorizes issue or PR as related to a bug"
  color: "FF0040"

- name: "kind/discussion"
  description: "Categorizes issue or PR as related to a discussion"
  color: "fbca04"

- name: "kind/documentation"
  description: "Categorizes issue or PR as related to documentation"
  color: "5319e7"

- name: "kind/feature"
  description: "Categorizes issue or PR as related to a new feature"
  color: "1d76db"

- name: "kind/question"
  description: "Categorizes issue or PR as related to a question"
  color: "cc317c"

- name: "kind/deprecation"
  description: "Categorizes issue or PR as related to a feature/enhancement marked for deprecation"
  color: "cc317c"

- name: "kind/cleanup"
  description: "Categorizes issue or PR as related to cleaning up code, process, or technical debt"
  color: "cc317c"

- name: "kind/support"
  description: "Categorizes issue or PR as a support question"
  color: "cc317c"

- name: "kind/security"
  description: "Categorizes issue or PR as related to a security process"
  color: "fbca04"

## PRIORITY

- name: "priority/critical"
  description: "Highest priority. This should be dealt with ASAP"
  color: "ee0701"

- name: "priority/high"
  description: "After critical issues are fixed, these should be dealt with before any further issues"
  color: "d93f0b"

- name: "priority/medium"
  description: "This issue or PR may be useful, and needs some attention"
  color: "fbca04"

- name: "priority/low"
  description: "This issue can probably be picked up by anyone looking to contribute to the project, as an entry fix"
  color: "0e8a16"

- name: "priority/backlog"
  description: "Possibly useful, but not yet enough support to actually get it done"
  color: "fbca04"

## STATUS

- name: "status/abandoned"
  description: "This issue or PR is no longer important"
  color: "000000"

- name: "status/available"
  description: "No one has claimed responsibility for resolving this issue"
  color: "c2e0c6"

- name: "status/blocked"
  description: "There is another issue or PR that needs to be resolved first"
  color: "ee0701"

- name: "status/in_progress"
  description: "This issue or PR is being worked on, and has someone assigned"
  color: "cccccc"

- name: "status/on_hold"
  description: "Similar to blocked, but is assigned to someone"
  color: "e99695"

- name: "status/proposal"
  description: "A new propoal"
  color: "d4c5f9"

- name: "status/review_needed"
  description: "The issue or PR needs to be reviewed"
  color: "fbca04"

## LIFECYCLE

- name: "lifecycle/waiting"
  description: "Indicates that an issue or PR is waiting a contributor."
  color: "75CA20"

- name: "lifecycle/active"
  description: "Indicates that an issue or PR is actively being worked on by a contributor."
  color: "75CA20"

- name: "lifecycle/frozen"
  description: "Indicates that an issue or PR should not be auto-closed due to staleness."
  color: "10D3EE"

- name: "lifecycle/stale"
  description: "Denotes an issue or PR has remained open with no activity and has become stale."
  color: "616F6C"

- name: "lifecycle/rotten"
  description: "Denotes an issue or PR that has aged beyond stale and will be auto-closed."
  color: "212F3D"

## SIZE

- name: "size/xs"
  description: "Size XS"
  color: "ededed"

- name: "size/s"
  description: "Size S"
  color: "ededed"

- name: "size/m"
  description: "Size M"
  color: "ededed"

- name: "size/l"
  description: "Size L"
  color: "ededed"

- name: "size/xl"
  description: "Size XL"
  color: "ededed"

## NEEDS

- name: "needs/triage"
  description: "Indicates an issue or PR lacks a `triage/foo` label and requires one."
  color: "D669BE"

- name: "needs/priority"
  description: "Indicates a PR lacks a `priority/foo` label and requires one."
  color: "D669BE"

- name: "needs/kind"
  description: "Indicates a PR lacks a `kind/foo` label and requires one."
  color: "D669BE"

- name: "needs/lifecycle"
  description: "Indicates a PR lacks a `lifecycle/foo` label and requires one."
  color: "D669BE"

- name: "needs/area"
  description: "Indicates an issue or PR lacks a `area/foo` label and requires one."
  color: "D669BE"

- name: "needs/size"
  description: "Indicates an issue or PR lacks a `size/foo` label and requires one."
  color: "D669BE"

- name: "needs/status"
  description: "Indicates an issue or PR lacks a `status/foo` label and requires one."
  color: "D669BE"

## AREA

- name: "area/github"
  description: "Github"
  color: "cc317c"

- name: "area/wolfi"
  description: "Wolfi"
  color: "cc317c"

## DEPENDENCY

- name: "dependency/github"
  description: "Dependency Github Actions"
  color: "6fcb70"

- name: "dependency/oci"
  description: "Dependency for container image"
  color: "6fcb70"

milestones:
- title: v1.0.0
  description: v1.0.0
  state: open
- title: v2.0.0
  description: v2.0.0
  state: open
