---
include: images/shell/prod.yaml

contents:
  packages:
    - apk-tools
    - build-base
    - git
    - vim
    - wget
    - wolfi-keys
    - socat
    - nftables
    - ethtool
    - ctop
    - bind-tools
accounts:
  run-as: root
