# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

---
name: OCI / Nginx

on: # yamllint disable-line rule:truthy
  schedule:
  - cron: "00 01 * * 1-5"
  pull_request:
    paths:
    - .github/workflows/nginx.yaml
    - "images/nginx/*.yaml"
  push:
    branches:
    - "main"
    paths:
    - .github/workflows/nginx.yaml
    - "images/nginx/*.yaml"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write
  security-events: write
  actions: read

jobs:
  publish:
    strategy:
      matrix:
        version: [latest] # , "1.27"]
        variant: [prod, shell, dev]
        include:
        - version: latest
          packages: ""
        # - version: "1.27"
        #   packages: 'nginx~1.27,nginx-package-config~1.27,nginx-mod-stream~1.27'
    name: ${{ matrix.version }}${{ matrix.variant == 'shell' && '-shell' || matrix.variant == 'dev' && '-dev' || '' }}
    uses: "./.github/workflows/release.yaml"
    with:
      repository: nlamirault/distroless/nginx
      config-dir: images/nginx
      tag: ${{ matrix.version }}${{ matrix.variant == 'shell' && '-shell' || matrix.variant == 'dev' && '-dev' || '' }}
      target: ${{ matrix.variant }}
      packages: ${{ matrix.packages }}
    secrets: inherit
