---
name: OCI / Nginx

on:
  schedule:
    - cron: "00 01 * * 1-5"
  pull_request:
    paths:
      - .github/workflows/nginx.yaml
      - 'images/nginx/*.yaml'
  push:
    branches:
      - 'main'
    paths:
      - .github/workflows/nginx.yaml
      - 'images/nginx/*.yaml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write
  security-events: write
  actions: read

jobs:
  publish:
    strategy:
      matrix:
        version: [latest, "1.27", "1.26", "1.25"]
        variant: [prod, shell, dev]
        include:
          - version: latest
            packages: ''
          - version: "1.27"
            packages: 'nginx~1.27,nginx-package-config~1.27,nginx-mod-stream~1.27'
          - version: "1.26"
            packages: 'nginx~1.26,nginx-package-config~1.26,nginx-mod-stream~1.26'
          - version: "1.25"
            packages: 'nginx~1.25,nginx-package-config~1.25,nginx-mod-stream~1.25'
    name: ${{ matrix.version }}${{ matrix.variant == 'shell' && '-shell' || matrix.variant == 'dev' && '-dev' || '' }}
    uses: './.github/workflows/release.yaml'
    with:
      tag: ${{ matrix.version }}${{ matrix.variant == 'shell' && '-shell' || matrix.variant == 'dev' && '-dev' || '' }}
      target: ${{ matrix.variant }}
      packages: ${{ matrix.packages }}
    secrets: inherit
